# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

source "https://rubygems.org"

gem 'fastlane', '>= 2.110.0'
gem 'cocoapods', '>= 1.11.0'
gem 'danger', '>= 5.6.5'
gem 'danger-swiftlint', '>= 0.17.4'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
